@startuml

actor Administrator as adm

left to right direction

adm --> (UC01 - Register new backoffice users via an out-of-band process)
adm-->  (UC08 - Create a new patient profile)
adm-->  (UC09 - Edit an existing patient profile)
adm-->  (UC10 - Delete a patient profile)
adm-->  (UC11 - List/search patient profiles by different attributes)
adm-->  (UC12 - Create a new staff profile)
adm-->  (UC13 - Edit a staff’s profile)
adm-->  (UC14 - Deactivate a staff profile)
adm-->  (UC15 - List/search staff profiles)
adm-->  (UC20 - Add new types of operations)
adm-->  (UC21 - Edit existing operation types)
adm-->  (UC22 - Remove obsolete or no longer performed operation types)
adm-->  (UC23 - List/search operation types)

actor BackofficeUser as bu

bu --> (UC02 - Reset my password if I forget it)
bu --> (UC06 - Log in to the system using my credentials,)

actor Patient as p

p --> (UC3 - Register for the healthcare application)
p --> (UC4 - Update my user profile)
p --> (UC5 - Delete my account and all associated data)
p --> (UC7 - Log in to the healthcare system using my external IAM credentials)


actor Doctor as doc

doc --> (UC16 - Request an operation)
doc --> (UC17 - Update an operation requisition)
doc --> (UC18 - Remove an operation requisition)
doc --> (UC19 - List/search operation requisitions)

@enduml